"""
Gaussian Decomposition of Momemura Optimization Results.

This module provides tools to analyze the Gaussian part of the optical circuit
before PNR measurements, decomposing it into an equivalent pure Gaussian state
generated by single-mode squeezers and passive linear optics.
"""

import numpy as np
from typing import Dict, Any, Tuple


HBAR = 2.0

def get_bs_symplectic(theta: float, phi: float, N_modes: int, modeA: int, modeB: int) -> np.ndarray:
    """
    Construct a 2N x 2N symplectic matrix for a beam splitter on modeA and modeB.
    Ordering: x1, ..., xN, p1, ..., pN.
    """
    U = np.eye(N_modes, dtype=complex)
    t = np.cos(theta)
    r = np.sin(theta)

    # Mode (Heisenberg) transformation a_out = U @ a implemented by the
    # Fock-space beam splitter U_BS = exp(theta (e^{iphi} a^dag b - e^{-iphi} a b^dag))
    # used by the JAX breeding sim and independent_verifier. That generator gives
    #   a_out_A =  t a_A + e^{ iphi} r a_B
    #   a_out_B = -e^{-iphi} r a_A + t a_B
    # (The previous version stored the TRANSPOSE of this matrix, i.e. it flipped
    #  the reflection direction of the beam splitter, which is not a single-mode
    #  unitary and made the moment-space path disagree with the Fock-space paths.)
    U[modeA, modeA] = t
    U[modeA, modeB] = np.exp(1j * phi) * r
    U[modeB, modeA] = -np.exp(-1j * phi) * r
    U[modeB, modeB] = t
    
    S = np.block([
        [np.real(U), -np.imag(U)],
        [np.imag(U),  np.real(U)]
    ])
    return S

def measure_homodyne(V: np.ndarray, mu: np.ndarray, idx: int, N_modes: int, x_val: float) -> Tuple[np.ndarray, np.ndarray]:
    """
    Project a pure Gaussian state onto a position eigenstate |x_val> for mode `idx`.
    Returns the reduced (2(N-1) x 2(N-1)) covariance matrix and mean vector.
    """
    x_idx = idx
    p_idx = idx + N_modes
    
    B11 = V[x_idx, x_idx]
    
    # Identify indices to keep (maintaining x1..x_N-1, p1..p_N-1 ordering)
    keep_x = [i for i in range(N_modes) if i != x_idx]
    keep_p = [i for i in range(N_modes, 2 * N_modes) if i != p_idx]
    keep_indices = keep_x + keep_p
    
    c = V[keep_indices, x_idx]
    
    V_A = V[np.ix_(keep_indices, keep_indices)]
    V_new = V_A - np.outer(c, c) / B11
    
    mu_A = mu[keep_indices]
    mu_new = mu_A + (x_val - mu[x_idx]) / B11 * c
    
    return V_new, mu_new

def apply_final_gaussian_symplectic(V: np.ndarray, mu: np.ndarray, final_gauss: Dict[str, Any], mode_idx: int, N_modes: int) -> Tuple[np.ndarray, np.ndarray]:
    """
    Apply the final Gaussian operations S(r, phi) R(varphi) D(disp) to the root signal mode.
    """
    r = float(final_gauss.get("r", 0.0))
    phi = float(final_gauss.get("phi", 0.0))
    varphi = float(final_gauss.get("varphi", 0.0))
    disp = complex(final_gauss.get("disp", 0.0))
    
    # 1. Squeeze S(z) where z = r * exp(i * 2phi)
    # Thewalrus convention for symplectic squeezing matrix:
    # S(r, phi) = [ [cosh r - sinh r cos phi, -sinh r sin phi], [-sinh r sin phi, cosh r + sinh r cos phi] ]
    # Wait, momemura's convention in independent_verifier:
    # K_squeeze = (r / 2.0) * (exp(-2j*phi) a^2 - exp(2j*phi) adag^2)
    
    # It is easier to construct the 2x2 symplectic matrix and embed it.
    # U_rot = diag(exp(i * n * varphi)) -> Phase rotation by varphi
    # Symplectic rotation matrix:
    R_mat = np.array([
        [np.cos(varphi), -np.sin(varphi)],
        [np.sin(varphi),  np.cos(varphi)]
    ])
    
    # Squeeze: r along angle phi. (In independent_verifier: S(z) with z = r*exp(i*2*phi))
    # Standard symplectic squeeze:
    S_sq = np.array([
        [np.cosh(r) - np.sinh(r)*np.cos(2*phi), -np.sinh(r)*np.sin(2*phi)],
        [-np.sinh(r)*np.sin(2*phi),              np.cosh(r) + np.sinh(r)*np.cos(2*phi)]
    ])
    
    S_2x2 = R_mat @ S_sq
    
    # Embed into 2N x 2N symplectic matrix
    S = np.eye(2 * N_modes)
    S[mode_idx, mode_idx] = S_2x2[0, 0]
    S[mode_idx, mode_idx + N_modes] = S_2x2[0, 1]
    S[mode_idx + N_modes, mode_idx] = S_2x2[1, 0]
    S[mode_idx + N_modes, mode_idx + N_modes] = S_2x2[1, 1]
    
    V_new = S @ V @ S.T
    
    # Displacement
    mu_new = S @ mu
    scale = np.sqrt(2 * HBAR)
    mu_new[mode_idx] += scale * np.real(disp)
    mu_new[mode_idx + N_modes] += scale * np.imag(disp)
    
    return V_new, mu_new

def compute_equivalent_gaussian(params: Dict[str, Any], light: bool = False) -> Dict[str, Any]:
    """
    Decompose the optimization result into an equivalent pure Gaussian state
    pre-PNR measurements.

    Args:
        light: skip the Williamson/Bloch-Messiah architecture extraction
               (squeezings, U_passive) -- returns only the moments and mode
               bookkeeping.  Use for bulk re-scoring where only cov/mu/
               signal_idx/control_idx/pnr_outcomes/homodyne_densities matter.

    Returns:
        Dict with:
            - num_initial_modes: int
            - num_homodyne_measurements: int
            - num_final_modes: int
            - squeezings_r: List[float] (the r values of the Williamson decomposition)
            - max_squeezing_r: float
            - max_squeezing_db: float
            - final_mu: List[Tuple[float, float]] (x, p displacements for each mode)
            - modes: List[Dict] (metadata for each remaining mode)
    """
    from frontend.independent_verifier import _build_gaussian_moments
    
    leaf_params = params["leaf_params"]
    leaf_active = params["leaf_active"]
    mix_params = params["mix_params"]
    
    # Find active leaves and their modes
    def get_leaf_val(key, idx):
        arr = leaf_params[key]
        if hasattr(arr, "__getitem__"):
            return arr[idx]
        return arr

    initial_modes = []
    blocks_V = []
    blocks_mu = []
    
    total_initial_modes = 0
    
    for i in range(8):
        if not bool(leaf_active[i]):
            continue
            
        n_ctrl = int(get_leaf_val("n_ctrl", i))
        N_leaf = n_ctrl + 1
        total_initial_modes += N_leaf
        
        # Build initial Gaussian moments for this leaf
        r_vec = np.array(get_leaf_val("r", i), dtype=float)
        phases_vec = np.array(get_leaf_val("phases", i), dtype=float)
        disp_vec = np.array(get_leaf_val("disp", i))
        
        mu_leaf, V_leaf = _build_gaussian_moments(r_vec, phases_vec, disp_vec, N_leaf)
        blocks_V.append((N_leaf, V_leaf))
        blocks_mu.append((N_leaf, mu_leaf))
        
        pnr_raw = get_leaf_val("pnr", i)
        if hasattr(pnr_raw, "tolist"):
            pnr_list = pnr_raw.tolist()
        elif isinstance(pnr_raw, list):
            pnr_list = pnr_raw
        else:
            pnr_list = [pnr_raw]
        pnr_outcomes = [int(p) for p in pnr_list[:n_ctrl]]
        
        initial_modes.append({"type": "signal", "leaf": i, "id": f"Leaf {i} Signal"})
        for c in range(n_ctrl):
            initial_modes.append({"type": "control", "leaf": i, "pnr_idx": c, "id": f"Leaf {i} PNR {c+1}", "pnr_val": pnr_outcomes[c]})

    # Assemble global V and mu
    V_global = np.zeros((2 * total_initial_modes, 2 * total_initial_modes))
    mu_global = np.zeros(2 * total_initial_modes)
    
    offset = 0
    for N_leaf, V_leaf in blocks_V:
        # V_leaf is in (x1..x_N, p1..p_N) format
        # We need to map it to the global (x1..x_total, p1..p_total) format
        for x_idx in range(N_leaf):
            for y_idx in range(N_leaf):
                V_global[offset + x_idx, offset + y_idx] = V_leaf[x_idx, y_idx]
                V_global[offset + x_idx, total_initial_modes + offset + y_idx] = V_leaf[x_idx, N_leaf + y_idx]
                V_global[total_initial_modes + offset + x_idx, offset + y_idx] = V_leaf[N_leaf + x_idx, y_idx]
                V_global[total_initial_modes + offset + x_idx, total_initial_modes + offset + y_idx] = V_leaf[N_leaf + x_idx, N_leaf + y_idx]
        offset += N_leaf
        
    offset = 0
    for N_leaf, mu_leaf in blocks_mu:
        mu_global[offset : offset + N_leaf] = mu_leaf[:N_leaf]
        mu_global[total_initial_modes + offset : total_initial_modes + offset + N_leaf] = mu_leaf[N_leaf:]
        offset += N_leaf
        
    modes = list(initial_modes)
    N_current = total_initial_modes
    num_homodyne = 0
    homodyne_densities = []   # Gaussian density p(x=hx) of each homodyne node

    # Get signal mode indices from the list of modes
    def get_signal_index(leaf_idx):
        for i, m in enumerate(modes):
            if m["type"] == "signal" and m["leaf"] == leaf_idx:
                return i
        return None

    # Mixing tree
    hx_raw = params.get("homodyne_x", 0.0)
    if hasattr(hx_raw, "__len__") and not isinstance(hx_raw, str):
        hx_values = [float(x) for x in hx_raw]
    else:
        hx_values = [float(hx_raw)] * 7
    while len(hx_values) < 7:
        hx_values.append(0.0)
    
    # Layer 1: mix leaves (0,1), (2,3), (4,5), (6,7)
    # Layer 2: mix layer1 outputs: pairs (0,1) and (2,3) -> mixing indices 4, 5
    # Layer 3: mix layer2 outputs: pair (0,1) -> mixing index 6
    
    # Track the active "root" leaf index that represents the signal mode traveling up the tree
    active_signals = []
    for i in range(8):
        if bool(leaf_active[i]):
            active_signals.append(i)
        else:
            active_signals.append(None)
            
    mix_node_idx = 0
    for layer, num_pairs in [(1, 4), (2, 2), (3, 1)]:
        next_active_signals = []
        for j in range(num_pairs):
            theta = float(mix_params[mix_node_idx][0])
            phi = float(mix_params[mix_node_idx][1])
            hx = hx_values[mix_node_idx]
            
            sigA_leaf = active_signals[2*j]
            sigB_leaf = active_signals[2*j + 1]
            
            if sigA_leaf is not None and sigB_leaf is not None:
                idxA = get_signal_index(sigA_leaf)
                idxB = get_signal_index(sigB_leaf)
                
                # Apply BS
                S = get_bs_symplectic(theta, phi, N_current, idxA, idxB)
                V_global = S @ V_global @ S.T
                mu_global = S @ mu_global
                
                # Measure mode B (idxB) via Homodyne.  Record the Gaussian
                # density p(x=hx) first -- the moment-space counterpart of the
                # Fock sim's p_x_density (same hbar=2 x-units); needed to
                # reconstruct the joint success probability exactly.
                _B11 = V_global[idxB, idxB]
                homodyne_densities.append(float(
                    np.exp(-0.5 * (hx - mu_global[idxB]) ** 2 / _B11)
                    / np.sqrt(2.0 * np.pi * _B11)))
                V_global, mu_global = measure_homodyne(V_global, mu_global, idxB, N_current, hx)
                modes.pop(idxB)
                N_current -= 1
                num_homodyne += 1
                
                next_active_signals.append(sigA_leaf)
                
            elif sigA_leaf is not None:
                next_active_signals.append(sigA_leaf)
            elif sigB_leaf is not None:
                next_active_signals.append(sigB_leaf)
            else:
                next_active_signals.append(None)
                
            mix_node_idx += 1
        active_signals = next_active_signals

    # Final Gaussian
    if "final_gauss" in params and params["final_gauss"]:
        final_sig_leaf = [s for s in active_signals if s is not None][0]
        root_idx = get_signal_index(final_sig_leaf)
        V_global, mu_global = apply_final_gaussian_symplectic(V_global, mu_global, params["final_gauss"], root_idx, N_current)
        
    if light:
        # cheap squeezing estimate from covariance eigenvalues (pure state:
        # eigvals = e^{±2r}); skip Bloch-Messiah entirely
        ev = np.clip(np.sort(np.linalg.eigvalsh(0.5 * (V_global + V_global.T)))[::-1],
                     1e-15, None)
        r_squeezings = np.sort(np.abs(0.5 * np.log(ev[:N_current])))[::-1].tolist()
        max_r = r_squeezings[0] if r_squeezings else 0.0
        max_db = max_r * 10 * np.log10(np.exp(2))
        U_passive = None
    else:
        # Extract squeezing values and passive unitary via Williamson + Bloch-Messiah
        from thewalrus.decompositions import williamson, blochmessiah

        # Williamson decomposition: V = S_W * D * S_W^T
        # For a pure state, D is proportional to Identity, so S_W is the exact symplectic matrix generating the state.
        D_W, S_W = williamson(V_global)

        # Bloch-Messiah: S_W = O1 * D_sq * O2
        O1, D_sq, O2 = blochmessiah(S_W)

        # D_sq is a diagonal matrix: diag(exp(-r1), ..., exp(-rN), exp(r1), ..., exp(rN))
        # We extract r values from the first N_current diagonal elements
        r_all = -np.log(np.diag(D_sq)[:N_current])

        # Sort descending
        sort_idx = np.argsort(np.abs(r_all))[::-1]
        r_squeezings = np.abs(r_all[sort_idx]).tolist()

        max_r = r_squeezings[0] if r_squeezings else 0.0
        max_db = max_r * 10 * np.log10(np.exp(2))

        # The passive network is described by the orthogonal symplectic matrix O1
        X = O1[:N_current, :N_current]
        Y = O1[N_current:, :N_current]
        U_passive = X + 1j * Y

        # Reorder columns of U to match the sorted squeezings
        U_passive = U_passive[:, sort_idx]
    
    final_mu_list = []
    for i in range(N_current):
        final_mu_list.append((float(mu_global[i]), float(mu_global[N_current + i])))

    # Identify the heralded signal mode and the PNR-measured control modes.
    # V_global / mu_global use xp-ordering (x_0..x_{N-1}, p_0..p_{N-1}), hbar=2,
    # with vacuum covariance = Identity (matches the Hanamura paper convention).
    signal_idx = None
    control_idx = []
    pnr_outcomes = []
    for i, m in enumerate(modes):
        if m["type"] == "control":
            control_idx.append(i)
            pnr_outcomes.append(int(m.get("pnr_val", 0)))
        else:
            if signal_idx is None:
                signal_idx = i

    return {
        "num_initial_modes": total_initial_modes,
        "num_homodyne_measurements": num_homodyne,
        "num_final_modes": N_current,
        "squeezings_r": r_squeezings,
        "max_squeezing_r": float(max_r),
        "max_squeezing_db": float(max_db),
        "final_mu": final_mu_list,
        "modes": modes,
        "U_passive": U_passive,
        # Full pre-PNR Gaussian state (control-mode representation source):
        "cov": V_global,
        "mu": mu_global,
        "signal_idx": signal_idx,
        "control_idx": control_idx,
        "pnr_outcomes": pnr_outcomes,
        "homodyne_densities": homodyne_densities,
    }
